### ISSUE TITLE
MessageNavigation

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#10]
- Only appears on desktop
- Contains previous / next navigation buttons (but not pagination)

<img width="235" alt="screen shot 2016-09-01 at 1 23 25 pm" src="https://cloud.githubusercontent.com/assets/354277/18183032/5a90a91c-7047-11e6-8ac5-54a5445cec4a.png">

Blocks #3

**Comment by ahelkit** [comment]
@webinista @U-DON In the folder view, can we have the previous/next buttons be in a disabled state (#5B616B) until there are enough messages to have another page, then the next button would be active. Let me know if that makes sense and if this is the right place to note that. Thanks!

**Comment by U-DON** [comment]
@angel Sure, we can do that. What should the disabled state for these buttons look like?

**Comment by ahelkit** [comment]
@U-DON Cool, just grayed out to #5B616B for the color and the border color.
