### ISSUE TITLE
Adding attachments

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#100]
(Creating a new issue, even though it's more of a note.)

Veterans can add attachments using an [input element](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/messaging/components/compose/MessageAddAttachment.jsx) (`input#messageAttachments`). The `multiple` attribute allows multiple uploads.

When the value of this field changes, it creates a `FileList` object. `FileList` is how we're generating the UI for [uploading attachments](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/messaging/components/compose/MessageUploadedAttachment.jsx). 

`FileList` objects are read-only For security reasons, browsers only allow applications to set the value of `input[type=field]` to an empty string.

When the user deletes an attachment from the UI, it just removes it from the displayed list of uploaded files.  It _**DOES NOT**_ delete it from the `FileList` object, which is the value of `input#messageAttachments`.

When sending the form, we will need to compare the value of `state.message.attachments` to the `FileList` object (which mimics an array with numeric keys, but isn't one) and only upload the files in the `FileList` object that still exist in `state.message.attachments`.

I _think_ it's possible to do this with `FormData`. `FormData` automatically sends objects with a `multipart/form-data` content type. Otherwise, we can probably use the`FileReader` API.

**Comment by saneshark** [comment]
Please use multipart/form-data - any other alternative would require encoding and decoding both at client and server side. I plan on having more information on this soon. Technically you can experiment with attachments now, both posting and downloading them.

NOTE: these examples are in yaml, but you should be able to determine the host, and other steps necessary for completing the request. It looks like I accidentally checked in retrieving the session for one of them, you can ignore that and scroll further down and see the GET request.

[example of downloading attachments](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/support/vcr_cassettes/sm/messages/10616687/attachments/show.yml)

[example of uploading attachments](https://raw.githubusercontent.com/department-of-veterans-affairs/vets-api/master/spec/support/vcr_cassettes/sm/messages/10616687/create_multipart.yml)

The last one is subject to change, but it will only change slightly -- namely to support uploading more than a single file. Currently it can only do one.

**Comment by webinista** [comment]
To be clear @saneshark: the question on our end is not "Are we going to use `multipart/form-data`?" We are. The question is: "How can we upload only those files the veteran wants to upload since we can't change the value of `FileList`?" 

I mentioned that `FormData` uses `multipart/form-data` because it is a bonus of using the API. I just am not sure if we can use it, alone, or if we'll also need to use `FileReader`.

**Comment by webinista** [comment]
Closed in https://github.com/department-of-veterans-affairs/vets-website/commit/efdbff025c5bdec9c5e94a47adbb690d5a1ee47a
