### ISSUE TITLE
Message object should be reset when user sends a message

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#105]
Steps to reproduce:
1. Click _Compose a message_
2. Compose and send a message.
3. Repeat step 1.
4. Should see previous message's data still in form.

That shouldn't happen.

**Comment by webinista** [comment]
Thinking the best way to fix is by resetting the message object in `/reducers/messages.js` when the `SEND_MESSAGE_SUCCESS` action gets dispatched. Thoughts @U-DON?

**Comment by U-DON** [comment]
@webinista Yup, that sounds like a good way to do it.

**Comment by webinista** [comment]
I've [made this change](https://github.com/department-of-veterans-affairs/vets-website/commit/f7f529c8cf47553059d82f1797a79dcc1bdb5fb1) and committed it to a branch, but we're held up a little bit by some yet-to-be-resolved server errors. Once they're resolved, I'll make sure this actually works, then create a pull request.

See department-of-veterans-affairs/vets-api#292

**Comment by webinista** [comment]
Dang it. I closed the wrong issue in my commit message. This should still be open.

**Comment by webinista** [comment]
> Resetting the message object in /reducers/messages.js when the SEND_MESSAGE_SUCCESS action gets dispatched.

This did not work.

**Comment by U-DON** [comment]
Oh, right, the `message` in the state stored in the messages reducer isn't the compose message. You want to listen to it in the compose reducer. And set it back to the initial state upon getting the action.
