### ISSUE TITLE
Remove character count for messages

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#110]
Remove character count based on stakeholder feedback captured [here](https://github.com/department-of-veterans-affairs/kudos-team/issues/118) and [here](https://github.com/department-of-veterans-affairs/kudos-team/blob/master/SecureMessaging/SM-stakeholder-review.md).

**Comment by webinista** [comment]
😭! I guess the upside is that we can also close #61.

**Comment by ahelkit** [comment]
@webinista I know 😞, sorry for the trouble!
