### ISSUE TITLE
Make changes to sendReply use FormData

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#113]
Blocked by / related to #100 / department-of-veterans-affairs/vets-website#3460

**Comment by U-DON** [comment]
@webinista Do you mean change `sendReply` to use FormData? It seems there's no support for attachments on drafts (https://dsva.slack.com/archives/vetsgov-sm/p1477409107000012).

**Comment by webinista** [comment]
I meant both, actually. But since attachments aren't supported for drafts, yes, `sendReply` should also use `FormData`.
