### ISSUE TITLE
Remove "From" field from Compose screen?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#115]
Do we actually need to include it in the UI? Not sure it will be included with the API token and data from our authentication stuff, but the sender knows who they are.

(Also asked this in Slack, but wanted to track it here in case it gets lost.)

<img width="817" alt="screen shot 2016-10-21 at 11 57 57 am" src="https://cloud.githubusercontent.com/assets/354277/19608373/b6121b94-9785-11e6-8e01-752e4aeb5b18.png">

**Comment by ahelkit** [comment]
@webinista Let's remove it!
