### ISSUE TITLE
SM Accessibility testing

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#117]
We need to set up and run automated accessibility testing for Rx. Talking to @crwallace, it seems the steps are:

Create a file like this example from HCA that goes through each page of Rx and runs .axeCheck('.main') on it.
Then to run the tests, first start selenium: npm run selenium:bootstrap
Then run the accessibility tests: npm run build && npm run test:accessibility
Last time we were going through issues, @webinista and @U-DON seemed to prefer things just get assigned to one of you then reassigned later if needed, so going to assign to @webinista , as @U-DON has been focused more on the unit tests. Let me know if you want those switched though!
- Copied from department-of-veterans-affairs/vets-website#3500
- Related to department-of-veterans-affairs/vets-website#3499

**Comment by ayaleloehr** [comment]
dup of #160. closing
