### ISSUE TITLE
AlertBox component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#12]
Alert box that confirms that the veteran's message has been sent, along with a close button. 
Can import the `AlertBox` component from `rx.` 

[Prototype](https://marvelapp.com/159dfd8#14605160)

Blocks #75, #63

**Comment by webinista** [comment]
@ayaleloehr @angel @gina is this the same as the Disclaimer component? (See #13), or are we planning to add a component that confirms an action? (I was typing up issues and listening to the hierarchy while in the meeting, which means I was really only doing a little bit of both :-) )

**Comment by ayaleloehr** [comment]
Alert box [here](https://marvelapp.com/159dfd8#14605160) in the green box saying "your message has been sent", separate from this disclaimer.

**Comment by webinista** [comment]
Closing. Component is already built, just need to import it from `../common/components` and adjust to our needs.
