### ISSUE TITLE
Flesh out remaining search reducer tests

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#120]
Setting start, end dates is tested. Testing advanced search visibility is tested (But may need to be removed).

Need to add tests for:
- [x] Search term
- [x] From field
- [x] From - exact match
- [x] Subject field
- [x] Subject - exact match

Related to #119

**Comment by eli-lewis** [comment]
@ayaleloehr is this still necessary?  If so, i'll write the tests so this can be closed.

**Comment by U-DON** [comment]
@eli-lewis These are unit tests for parts of the front-end code.

**Comment by eli-lewis** [comment]
@U-DON ok... who should this be assigned to then?  you?  ;)

**Comment by U-DON** [comment]
It can be assigned to whomever picks up this part of the tests. I was already handling reducers in general, so I could do it too.
