### ISSUE TITLE
Unread messages not showing

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#129]
Currently on staging, there aren't any unread messages. Could we get one for usability testing?

Moved this [issue](https://github.com/department-of-veterans-affairs/vets-website/issues/3569) from vets-website repo.

**Comment by ayaleloehr** [comment]
@saneshark can you do this one?

**Comment by U-DON** [comment]
@angel Is this still relevant? The unread state of messages is quite volatile in that they'll immediately become read as you access them, and there is no way to undo it. So each time you need this, you'll have to request that someone with a test clinician account on MHV (I think @ayaleloehr and @saneshark may have access) send a few messages. I don't currently know of a better way to enable this test. If we're overall okay with this process, can we close this?

**Comment by saneshark** [comment]
Happy to set it up if we need to test it one more time, but I agree that it's a little bit of a pain to setup.

**Comment by ahelkit** [comment]
@U-DON not sure, I copied this issue from [here](https://github.com/department-of-veterans-affairs/vets-website/issues/3569). @gnakm do we still need this?

**Comment by gnakm** [comment]
This is an old issue and Alex has a test clinician account. I don't think we'll be testing within the next week unless I am unaware of something. I think we can close this. Please open if you feel necessary.
