### ISSUE TITLE
Disclaimer component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#13]
Closable disclaimer box urging veterans to call the crisis line if this is urgent.

<img width="1233" alt="screen shot 2016-09-01 at 12 33 20 pm" src="https://cloud.githubusercontent.com/assets/354277/18181528/5862b416-7040-11e6-8831-0345a938ba6c.png">

Similar to the [Prescriptions disclaimer](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/rx/components/Disclaimer.jsx).

Blocks #11

**Comment by webinista** [comment]
@angel and possibly @gnakm Some questions for you:
- Should the link to Veterans Crisis Line point directly to https://www.veteranscrisisline.net/?
- The latest [prescription mockups](https://marvelapp.com/iaa9b9) use a collapsible warning/disclaimer box instead of a closable one. Can we / Should we do the same here?

**Comment by ahelkit** [comment]
@webinista yes to both! Will update mocks to reflect the collapsible disclaimer box.

**Comment by gnakm** [comment]
@webinista Would it be possible to put a hold on this? Unlike Rx, we think the disclaimer is going to be a lot shorter and want to verify legal disclaimers with stakeholder.

**Comment by webinista** [comment]
Sure @gnakm. We haven't started work on this yet. Just update this ticket when you have the disclaimer language.

**Comment by webinista** [comment]
Assigning this to Gina for now, mostly to indicate that it's not ready to work on yet. When the disclaimer language is finalized, this can be reassigned back to the front end team.

**Comment by gnakm** [comment]
Sounds good. We'll have a better idea of the disclaimer after we having our design meeting with Dr Douglas and Evans.

**Comment by webinista** [comment]
Any updates?

**Comment by gnakm** [comment]
Closing because this was resolved and implemented.
