### ISSUE TITLE
Make "Compose a message" button bigger 

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#130]
Can we make the top and bottom padding 1.75rem and the font size the closer to 18px like so:

![image](https://cloud.githubusercontent.com/assets/13420618/19873523/cf69c62e-9f95-11e6-8ff1-923176d9ad77.png)

Move [issue](https://github.com/department-of-veterans-affairs/vets-website/issues/3614) from vets-website repo here.

**Comment by webinista** [comment]
Is this for both mobile and desktop?
