### ISSUE TITLE
Number of messages in thread next to recipient name in folder view

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#135]
![image](https://cloud.githubusercontent.com/assets/103496/19874277/387d9114-9f81-11e6-8614-16f8ed7e1110.png)

Messages with threads should have the number of messages in that thread next to the recipient name like so: 
![image](https://cloud.githubusercontent.com/assets/103496/19874300/55278612-9f81-11e6-8c19-33ab5cd020c8.png)

Moved [issue](https://github.com/department-of-veterans-affairs/vets-website/issues/3621) from vets-website to here.

**Comment by ayaleloehr** [comment]
I don't believe this is possible at this time given the API. @mphprogrammer or @saneshark can you confirm?

**Comment by mphprogrammer** [comment]
We might be able to provide the number of messages in the metadata of the returned collection, let me check ...

**Comment by ayaleloehr** [comment]
Where did this land @mphprogrammer ?  I'm still of the opinion we don't have this information in the API when getting a folder.

**Comment by mphprogrammer** [comment]
Sorry - I completely misread this issue. @ayaleloehr is absolutely right - folder message information is not-thread aware.

**Comment by ayaleloehr** [comment]
So let's say this not in scope for Veterans day, but we should leave it open in the backlog, as it is a change we would like from the MHV APIs in the future that I don't want it to be lost!

**Comment by eli-lewis** [comment]
@ayaleloehr are we ready to move forward with this and assign it to someone?

**Comment by ayaleloehr** [comment]
This is not possible currently given the API. Closing as un-actionable at this time.
