### ISSUE TITLE
Error when deleting a name in "Create new folder" modal

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#139]
Right now when you are in the "Create new folder" modal and put in a name and then delete it all the way an error automatically pops up before the Veteran even tried submitting it. The error shouldn't show up, but I think a better experience would be to have the initial state of the modal have the "Create" button disabled until something typed into the modal. So we don't allow Veterans to even submit blank folder names.

**Comment by webinista** [comment]
> Right now when you are in the "Create new folder" modal and put in a name and then delete it all the way an error automatically pops up before the Veteran even tried submitting it.

This is consistent with how we're handling error messages across the site. See the [healthcare application](https://www.vets.gov/healthcare/apply/application/veteran-information/personal-information) for an example.

The one real change is that the error checking is done `onBlur`, in newer apps (e.g., not healthcare). It's triggered when the user un-focuses from that field. I'm going to punt this over to the main vets-website repo / Vanguard team. (See department-of-veterans-affairs/vets-website#3753)

>  but I think a better experience would be to have the initial state of the modal have the "Create" button disabled until something typed into the modal.

This is easy enough to do.
