### ISSUE TITLE
SearchBox component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#14]
- Needs input field + submit button
- Mobile search button should use magnifying glass icon. 
  - Use `usa-sr-only` class to hide _Search_ text off screen. 
  - Also recommend putting SVG inline with `style="pointer-events:none;`, but not strictly necessary. Can also use a background image.
- Include _Advanced search_ button that reveals / collapses [AdvancedSearch](department-of-veterans-affairs/messaging-fe/issues/4) component.
- Search box should take up full width of parent container. 
#### Mobile view

<img width="251" alt="screen shot 2016-09-01 at 12 56 07 pm" src="https://cloud.githubusercontent.com/assets/354277/18182154/8196a52e-7043-11e6-93da-f92dafeab4bf.png">
#### Desktop view

<img width="749" alt="screen shot 2016-09-01 at 1 08 02 pm" src="https://cloud.githubusercontent.com/assets/354277/18182529/32a4d934-7045-11e6-98d8-2104538ffe89.png">

Blocked by #4 (AdvancedSearch component)

**Comment by webinista** [comment]
Recommend using FlexBox (`display: flex` is enough) on the parent component for the search box. Would not worry about making it fill the full container width in browsers <= IE10. Stick a `float: left` on both the input box and the button. Maybe put the `display: flex` stuff within an `@supports` block.

**Comment by webinista** [comment]
Question for product / design @staceylanger @angel 

What happens if the veteran tries to submit an empty search?

**Comment by gnakm** [comment]
## Error for empty search

<img width="259" alt="screen shot 2016-09-08 at 7 56 07 pm" src="https://cloud.githubusercontent.com/assets/13420618/18370952/bb60b5cc-75fe-11e6-85e5-b9300cf0c4f1.png">

**Comment by gnakm** [comment]
Desktop view

![search error](https://cloud.githubusercontent.com/assets/13420618/18384571/49315244-7659-11e6-9afb-059f03161251.png)

**Comment by webinista** [comment]
HTML is built, but since there's an outstanding question about how search should function, I'm going to suspend further work on it. 

See department-of-veterans-affairs/vets-api#94 and #40
