### ISSUE TITLE
Move Advanced Search error message to below the folder title

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#141]
Currently, there's an `AlertBox` component build into the `MessagingApp` container. 

![screen shot 2016-11-01 at 16 49 43-fullpage](https://cloud.githubusercontent.com/assets/354277/19911826/4569f476-a053-11e6-9fae-97c2c7a9b0d0.png)

However, the design (see #93) says that the error message should appear just above the search box and below the folder title.

![](https://cloud.githubusercontent.com/assets/13420618/18384555/23eb2de8-7659-11e6-9d9d-da3087a0b408.png)

Need to move it.

**Comment by U-DON** [comment]
Initial thought is to split alerts state into two objects; one for the overall app (`appAlert`) and one for the search (`searchAlert`).

**Comment by U-DON** [comment]
After removing the error that comes up after empty search, I don't think this is relevant anymore, since there aren't other errors that would occur with search. Closing.
