### ISSUE TITLE
Search bug: URL params replaces instead of updates?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#142]
**Steps to reproduce:**

1. Click advanced search. Type in "Kam" in the From field and click search. results come back, which is expected. 
2. Check the "Exact match" box. Click search. no results come back, which is expected. 
3. Uncheck the "Exact match box". Click search. no results come back, which is unexpected.

I believe in 1 and 3 the URL after hitting "search" for each one should be the same, but it seems to be different with an extra `filter` or something being left in there in 3. Not totally sure though.

(This is something @ayaleloehr noticed)

**Comment by U-DON** [comment]
Closing since this doesn't seem to be happening anymore.
