### ISSUE TITLE
Should not be able to move messages to "drafts" or "deleted"

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#143]
<img width="1059" alt="screen shot 2016-11-02 at 1 15 55 pm" src="https://cloud.githubusercontent.com/assets/23019174/19939281/a26681ac-a0fe-11e6-8b8b-d6303f0fabd0.png">

Currently when looking at a message in inbox both draft and deleted show up and folder options and they should not.  Only options should be: folder names and create new folder

**Comment by eli-lewis** [comment]
Second issue related to move:  Move dropdown- Messages are not moving when a folder is selected.  Background for selected folder name is changing by no action is happening when folder is selected

**Comment by U-DON** [comment]
@ayaleloehr I believe the second issue ^ is due to the same issue with PATCH requests turning into OPTIONS.

**Comment by webinista** [comment]
~~This is partly done. Reassigning to you @ayaleloehr, because I _think_ you're the one investigating why our `PATCH` requests are no longer working.~~

Actually, I'm going to close this issue. Part B of this should now be tracked in #151.
