### ISSUE TITLE
All times in SM should specify that they are Eastern

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#145]
I had an outstanding item to ask MHV about timestamps... Turns out all times that MHV returns from their API are in Eastern time. So even if a doctor or Veteran is on the west coast, the time that will show up is Eastern. Carnetta asked that we write some variant of "Eastern time" wherever we show a timestamp. 

@angel preferences on how we do this?  Eastern? EST? EDT? ET?  I really don't know if one is best, but think that we should include something to be sure users are aware of what they are seeing is Eastern time.

**Comment by ahelkit** [comment]
@ayaleloehr there's no way to convert it to the Veteran's local time? If not, I think EST is most standard.

**Comment by ayaleloehr** [comment]
Thanks @angel . Will now turn to @webinista and @U-DON : what's your preferred way of going about this?  Should we show the local time for users or should we just put EST after each timestamp?

**Comment by U-DON** [comment]
@ayaleloehr It's easiest to just use EST. There is a library we can import to convert to local time, though. I think it'd be a better experience to see it in local time.

**Comment by ayaleloehr** [comment]
Scope decision: we will write EST next to timestamps for Veterans day. 

We will likely implement showing local time post initial launch.
