### ISSUE TITLE
SM won't load on IE11

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#146]
I went on the VA computer at 1800g today and SM wouldn't load on it. Here are a few screenshots:

View of page (it stayed like this indefinitely) 
<img width="1308" alt="loading" src="https://cloud.githubusercontent.com/assets/4719765/19953288/8acf9274-a142-11e6-972a-e3ccb24c4b50.png">

View of the developer console:
<img width="1333" alt="dev console" src="https://cloud.githubusercontent.com/assets/4719765/19953295/9a099fbe-a142-11e6-9308-c6c05a161645.png">

View of the IE version:
<img width="370" alt="ie version" src="https://cloud.githubusercontent.com/assets/4719765/19953297/a28039dc-a142-11e6-9ee9-72e94ce23cb8.png">

**Comment by webinista** [comment]
IE11 doesn't support `Object.assign`. I thought Babel.js was supposed to fix that.

**Comment by bshyong** [comment]
@webinista I believe Babel only transpiles syntax differences; if we're using functionality that isn't supported in certain browsers, we might need a polyfill for the missing ES6 functionality like `Object.assign`.

http://babeljs.io/docs/usage/polyfill/

http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign

> Note: Depending on what ES2015 methods you actually use, you may not need to use babel-polyfill or the runtime plugin. You may want to only load the specific polyfills you are using (like Object.assign) or just document that the environment the library is being loaded in should include certain polyfills.

**Comment by webinista** [comment]
Using assign from lodash so that we don't add another dependency.
