### ISSUE TITLE
Entering same date for start and end date in search query results in no messages

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#148]
Because we search from the beginning of the first date to the beginning of the second date, if you choose the same date for both, you don't get any messages unless it occurred at midnight on the dot. It's like searching for a message exactly at 11/1/2016 at midnight (00:00:00).

So the range is inclusive for the start date and exclusive for the second date. For it to work so that choosing the same date on both will return messages sent on that day, the end date of the range has to be inclusive.

**Comment by U-DON** [comment]
@angel Is it okay to make the date range search behave as proposed above?

Right now, the date range works from the beginning of the start date to the beginning of the end date, so the results don't include messages that were sent on that end date. I'd think that if I chose the same date (Nov 1, for example) for both, I should get the messages sent on that date (Nov 1), but with the way it is now, I wouldn't get anything in the results. For it to work that way, we need to include messages sent on the end date.

**Comment by ahelkit** [comment]
@U-DON that sounds great. I agree that if you do start to end with the same date you should get the results of that date. Thanks!
