### ISSUE TITLE
SM- print icon

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#150]
print icon needs to be hidden when viewing a message in every folder

**Comment by webinista** [comment]
Should we just remove it altogether or is there ever a case where we need to have a print icon?

**Comment by eli-lewis** [comment]
@ayaleloehr  Remove altogether, correct?

**Comment by ayaleloehr** [comment]
Yes, removed!  Will likely be added back later as an enhancement, but for Veterans day it should just not exist!
