### ISSUE TITLE
Messages are not being moved when a new folder is selected

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#151]
Separated from #143:

> Second issue related to move: Move dropdown- Messages are not moving when a folder is selected. Background for selected folder name is changing but no action is happening when folder is selected

Believed to be caused by `PATCH` requests turning into `OPTIONS.` (e.g.: This should be, and is sent as a `PATCH` request, but the server does not seem to support the `PATCH` method.

**Comment by saneshark** [comment]
The OPTIONS preflight check should not have anything to do with this. This is just how CORS works, it first makes a request to OPTIONS to see if the method is allowed, and then makes the PATCH request. If you are finding that a message cannot be moved, then that is a separate issue, but does not have to do with the initial CORS preflight OPTIONS check.

> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the set of origins that are permitted to read that information using a web browser.  Additionally, for HTTP request methods that can cause side-effects on user data (in particular, for HTTP methods other than GET, or for POST usage with certain MIME types), the specification mandates that browsers "preflight" the request, soliciting supported methods from the server with an HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method. Servers can also notify clients whether "credentials" (including Cookies and HTTP Authentication data) should be sent with requests.

**Comment by ayaleloehr** [comment]
I seem to be able to move messages successfully. Assigning back to @webinista to check as well. Thanks for looking into this @aub and @saneshark

**Comment by webinista** [comment]
I'm assigning to @U-DON who worked on this. (I still don't have VPN access). All I did was create a separate issue so that it didn't get lost.

**Comment by U-DON** [comment]
This is working for me now. For some reason, it didn't get past the OPTIONS check before. Closing.

Edit: Probably related, but I see that 'PATCH' is among the operations in `access-control-allow-methods` header in the response. It definitely wasn't there before, so perhaps something has changed.
