### ISSUE TITLE
RX- Column Sorting

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#152]
It's taking several clicks for column sorting triangle to show.  There are several times when despite numerous clicks, the sorting triangle never showed   

Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
authorization:Token token=pNPg1M9bk_W9csLPT5MYhkaQ1QPRWFvBMLwxKctB
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:staging-api.vets.gov
Origin:https://staging.vets.gov
Pragma:no-cache
Referer:https://staging.vets.gov/healthcare/messaging/folder/0?sort=sender_name
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
x-key-inflection:camel
Query String Parameters
view source
view URL encoded

**Comment by U-DON** [comment]
It should appear pointing down on the Date column by default. When you want to click the column header to sort, there will be some latency as with any other request, so it won't change until the data is returned.

I've seen the arrow not appear when it was sorting by an invalid value, but that was much earlier, and all of the fields should be sortable via the API now. So I think clicking in quick succession before the data is returned is causing some unintended side effects. Hopefully that will be mitigated when we add the loading screen to Messaging. But this is just speculation; not sure what is happening without more data (are the API requests successful, what fields were clicked, how many times were they clicked, did the request complete before clicking, etc.).

**Comment by eli-lewis** [comment]
retested this issue- sorting only takes one click now, however "loading" screen shows for a few seconds while request completes.  

@U-DON @ayaleloehr - i think this can be closed at this point.  There is a delay but the loading screen makes it obvious to the users.  Agree?

**Comment by ayaleloehr** [comment]
agree. closing.
