### ISSUE TITLE
Drafts can't have attachments

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#154]
@angel when we save a message as a draft, even if there are attachments attached to the message, these attachments are not able to be saved with the draft. This obviously isn't ideal but is a limitation of the API right now. Should we give a warning to the user when they are saving a draft that has attachments? is there some other way we could handle this from the UX?   Open to thoughts!

Hat tip to @eli-lewis for finding this in functional testing!

**Comment by saneshark** [comment]
Oh, i wrote up this exact thing just now too :)

Mine might be duplicate, but it includes screenshot https://github.com/department-of-veterans-affairs/messaging-fe/issues/155

**Comment by ayaleloehr** [comment]
Yours is better because it has a picture. Closing this one in favor of that.
