### ISSUE TITLE
Search button issue. 

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/messaging-fe#157]
Two things I noticed:

1) on chrome and all browsers, the button appears to have rounded corners on the right, but nothing else on the page has rounded corners so this seems like a bug?

2) On Safari I noticed that the text in the button is scrunched up near the end. 

<img width="1130" alt="safari search" src="https://cloud.githubusercontent.com/assets/591737/20077459/814dc984-a50a-11e6-8269-9b1f5bf48222.png">

**Comment by ahelkit** [comment]
@saneshark 
1. The search bar button should be rounded on the right like that in the [U.S. Web Design Standards](https://standards.usa.gov/search-bar/). The compose message button is rounded on all sides. Let me know if I didn't understand that properly. 
2. That should not be the case in Safari, it should look the same on all browsers.

**Comment by webinista** [comment]
@saneshark can you tell us more here? 
- What version of Safari are you using?
- What viewport is that (e.g.: how wide is the window? Is this on a tablet, etc)?

This is what I see in Safari 10, which is the latest version. 

![screen shot 2016-11-10 at 8 12 36 am](https://cloud.githubusercontent.com/assets/354277/20186143/a6b7d4ce-a723-11e6-8a9e-479eeec1cbd0.png)

**Comment by webinista** [comment]
Closing this since we can't duplicate.

**Comment by ahelkit** [comment]
This happened at the MHV coordinators demo today. @ayaleloehr can you share details with @webinista?

**Comment by ayaleloehr** [comment]
Here is a screenshot on my machine (15" mac laptop):

<img width="1323" alt="screen shot 2016-11-17 at 1 11 51 pm" src="https://cloud.githubusercontent.com/assets/4719765/20401590/703bde3c-acc7-11e6-821b-7ced454ba95e.png">

Safari Version:

<img width="188" alt="screen shot 2016-11-17 at 1 10 01 pm" src="https://cloud.githubusercontent.com/assets/4719765/20401596/7482acf0-acc7-11e6-8753-3872ded6aa10.png">

**Comment by webinista** [comment]
I don't have Safari 9 available to test. @saneshark @ayaleloehr can you verify whether this is fixed?

**Comment by ayaleloehr** [comment]
Staging still has this issue with Safari 9.1.3. Screenshot: 

<img width="1319" alt="screen shot 2016-11-29 at 5 52 45 pm" src="https://cloud.githubusercontent.com/assets/4719765/20732433/b03f6b4a-b65c-11e6-8d76-5eab1e008959.png">

**Comment by webinista** [comment]
I do not have a version of Safari 9 available to debug this. Does the button work at least? If you click it, will the search update?

**Comment by saneshark** [comment]
@webinista have you tried using the Safari emulator in chrome? It might not be perfect, but I wonder if that would identify this issue. I can try to play with it in browser / dev tools and see if I can come up with a fix if that the emulator doesn't work.

**Comment by webinista** [comment]
@saneshark The mobile emulator only modifies the viewport size. It doesn't change the rendering engine. This is a rendering engine issue that requires Safari 9/9.1 in order to duplicate and test.

**Comment by webinista** [comment]
@saneshark Can you checkout the [department-of-veterans-affairs/messaging-fe#157](https://github.com/department-of-veterans-affairs/vets-website/tree/department-of-veterans-affairs/messaging-fe%23157) branch and tell me whether removing that `flex` declaration worked?

**Comment by saneshark** [comment]
@webinista 

TYPO HERE: "va-flex--stretch" should probably be "va-flex-stretch"
<img width="644" alt="screen shot 2016-12-12 at 7 17 29 pm" src="https://cloud.githubusercontent.com/assets/591737/21122399/e18b2840-c09f-11e6-985b-cba5bad94a35.png">

Removing this `flex` setting appears to fix the issue for Safari, but did not test this on Chrome.
<img width="451" alt="screen shot 2016-12-12 at 7 18 07 pm" src="https://cloud.githubusercontent.com/assets/591737/21122385/ca4654fc-c09f-11e6-80c5-8d273359041a.png">

<img width="1093" alt="screen shot 2016-12-12 at 7 18 15 pm" src="https://cloud.githubusercontent.com/assets/591737/21122445/13c256d0-c0a0-11e6-8c5e-fcba85b2d684.png">

**Comment by saneshark** [comment]
~~Here is a Lifehacker article for installing Mac OS X on a windows machine within VirtualBox.~~ There are also a number of different websites that offer testing / browsing capabilities. I believe Adobe has a product available for Windows as well that allows you to simulate Safari.

~~http://lifehacker.com/5938332/how-to-run-mac-os-x-on-any-windows-pc-using-virtualbox~~

Ignore the lifehacker recommendation -- didn't realize it requires a hacked version of the installer! Doing the reverse of this for Internet Explorer on a Mac does not require any pirating.

**Comment by webinista** [comment]
Thanks for confirming that removing `flex: 0 1 5rem` fixes it. I created a pull request for the `department-of-veterans-affairs/messaging-fe#157` branch containing that fix.

(Also: `va-flex--stretch` is the correct class name.)
