### ISSUE TITLE
Downloading attachment

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/messaging-fe#159]
When I go to my sent folder and view a message that I sent having an attachment, I then click on the attachment to download it, and I get "Failed - Needs authorization"

<img width="862" alt="screen shot 2016-11-07 at 5 08 10 pm" src="https://cloud.githubusercontent.com/assets/591737/20077999/cd4edb00-a50c-11e6-9181-23750c87c59e.png">

**Comment by saneshark** [comment]
Is this still happening? I don't think this is a backend issue as we do not raise any errors like "Failed - Needs authorization." 

Could you please provide steps on how to recreate, what user to login as, etc, in the form of a user story? Also please include the JSON response we provide if possible, "Failed - needs authorization" is not something we provide to my knowledge.

**Comment by saneshark** [comment]
Oh, wow, nevermind, I just realized I was the one who opened this ticket! :)

I'll look into it. I can't remember why I created this or if it is still an issue.

**Comment by ayaleloehr** [comment]
@eli-lewis can you do a functional test on staging to determine if this is still a problem?  

If you need a message with attachments to test with, just let me know and I can send some from the provider side on staging.

**Comment by eli-lewis** [comment]
@ayaleloehr sure thing.  Does the attachment need to be something specific?  If not, then i'll just attach a word doc, otherwise, please send.

**Comment by ayaleloehr** [comment]
nothing specific.

**Comment by eli-lewis** [comment]
@ayaleloehr can't test b/c unable to send messages right now

**Comment by ayaleloehr** [comment]
I can replicate. Steps to recreate:
1. Open a thread in the inbox that has an attachment
1. Click the attachment link to download it
1. Attachment downloads saying "failed - Needs authorization"
1. If you right click the attachment link and open it in a new tab (like in the image below), you get `{"errors":[{"title":"Not authorized","detail":"Not authorized","code":"401","status":"401"}]}`

<img width="840" alt="screen shot 2016-12-21 at 12 59 41 am" src="https://cloud.githubusercontent.com/assets/4719765/21379027/d6fa90e4-c718-11e6-8654-5b3b16ee5a10.png">

@bshyong or @U-DON can you please prioritize this? I hope the API call to download the attachment just doesn't have the userToken attached to it. If it gets more complicated than that or there seems to be an API issue, please pull in @mphprogrammer

**Comment by eli-lewis** [comment]
tested, can send messages with attachments.  Closing issue

**Comment by U-DON** [comment]
This isn't closed yet. This is for downloading attachments, not sending them.
