### ISSUE TITLE
Add 508 Tests

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#160]

**Comment by eli-lewis** [comment]
have reached out to Jamie twice requesting meeting to discuss 508 testing for SM and Rx.  Will update here.

**Comment by eli-lewis** [comment]
talking with Jamie on Monday, 12/5

**Comment by eli-lewis** [comment]
Scheduled to go do 508 testing with auditors on Wednesday, 12/21 at 10:00 am

**Comment by bshyong** [comment]
Tests look good and are passing. Please open a new issue with results from auditor test when results are available. They will typically have a much more extensive scan that may catch additional issues.

![screen shot 2016-12-20 at 1 23 30 pm](https://cloud.githubusercontent.com/assets/303289/21368479/9bd27402-c6b7-11e6-8429-4b2e6551b98f.png)
