### ISSUE TITLE
Folder sorting triggers are not keyboard accessible

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#162]
Guessing they may need to become `button` elements instead of `a` elements.

**Comment by eli-lewis** [comment]
@U-DON is this the same/similar to as #168?

**Comment by webinista** [comment]
Similar fix for both, but these are for two different features. This is about the sort triggers for the table that displays messages. 

I _think_ the reason is that they're `a` elements with no `href` attribute, so they never get keyboard focus. If it's an `a` without an `href`, it should probably be a `button` element instead.
