### ISSUE TITLE
Rx- Mobile- Track package box not lining up

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#172]
![track package](https://cloud.githubusercontent.com/assets/23019174/20313907/6427403e-ab26-11e6-9a6b-6a45421a7b22.png)

**Comment by webinista** [comment]
What device is this (and/or what is the width of the viewport)?

**Comment by eli-lewis** [comment]
samsung 7

**Comment by webinista** [comment]
Would that be a Samsung Note 7 or Galaxy S7?

**Comment by eli-lewis** [comment]
Galaxy S7
