### ISSUE TITLE
Mobile pagination for folders

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#174]
There isn't currently a way to navigate through pages of messages within a folder in mobile view. What should it look like?

**Comment by ahelkit** [comment]
@U-DON I think for mobile, could we show one page and then if the Veteran tries to keep scrolling down there would be a loading symbol that appends the second page to the first page. It seems to be the standard practice for email clients. Let me know if that doesn't make sense.

Also, with that is it possible to fix the this part to the top for the folder? 
![image](https://cloud.githubusercontent.com/assets/103496/20320918/9b053eba-ab41-11e6-9548-2edecefacf62.png)
Do you know if we did that how many messages a Veteran would be able to see on their mobile screen? I want there to be a way out for them in case they scroll down really far and don't have a good way to scroll back up. Also, let me know if this should be in a different issue. 

Thanks!

**Comment by U-DON** [comment]
@angel Yeah, it should be possible to fix the controls to the top. I don't know for sure how many messages would show, but it looks like 3, assuming a resolution of 360x640.

I think the load more on scroll can work, but we haven't done something like that yet, so it could take a bit of work to incorporate.

**Comment by U-DON** [comment]
Actually, can we show the desktop pagination controls for now? I think trying to get infinite scroll working on this will change quite a bit in how we handle the state of the app, and we probably just want something that works for the short term.

**Comment by ayaleloehr** [comment]
@angel you good with this (desktop controls for now with goal of getting to infinite scroll)?

**Comment by ahelkit** [comment]
@U-DON @ayaleloehr works for me! Thanks!
