### ISSUE TITLE
Searches that yield no results will display, "You have no messages in this folder"

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#175]
This doesn't enable the user to try a different search since it treats the results as an empty folder instead of saying that there were no results. So it forces the user to go back in order to use the search again.

Solution might be to show the search form and a different message if there is a truthy value for `filter`.

**Comment by eli-lewis** [comment]
![no new messages](https://cloud.githubusercontent.com/assets/23019174/20769477/10ce8096-b710-11e6-9b92-cd7568ab4b39.JPG)
