### ISSUE TITLE
Change 72 hours to three working days in success message

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#178]
We had a meeting with coordinators and we had a great suggestion to change "72 hours" to "Three working days". Reasoning: "So not to create an expectation that when a Vet sends a msg on Thursday they wont expect the reply by Sunday/ Holidays."

**The new message should be:**
"Your message has been sent. View message. Please allow up to three working days for a response from your health care team."

**Comment by ayaleloehr** [comment]
Would love to get this in today @webinista . Will show coordinators that we're moving quickly on their feedback, which would be awesome!
