### ISSUE TITLE
Remove colons from field labels and change to regular weight

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#183]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), to be consistent with our design patterns, please remove the colons and change the text to regular weight. 

![image](https://cloud.githubusercontent.com/assets/103496/20723381/22771da4-b61f-11e6-9474-f4d7b33f80f9.png)

![image](https://cloud.githubusercontent.com/assets/103496/20724738/39c96214-b624-11e6-90ea-bcc566b010ed.png)

**Comment by webinista** [comment]
I'm pretty sure this was completed as part of department-of-veterans-affairs/vets-website#4167.
