### ISSUE TITLE
Attachment [x] button should be top right

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#184]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), attachment [x] button should attach to the top right corner rather than bottom right.

<img width="391" alt="screen shot 2016-11-28 at 2 29 36 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688789/2fb7539c-b577-11e6-994a-036c6f8a7f3c.png">

**Comment by webinista** [comment]
@angel how should we handle extra-long file names?  We can leave it as is (wrapping text, with some possible overlap of the button and file name). Or we can do what we've done with extra long folder names and use `text-overflow: ellipsis`.

**Comment by ahelkit** [comment]
@webinista Let's go with wrapping. I think it's nice to see the full name and extension to confirm that that's the file you wanted to attach. 

![image](https://cloud.githubusercontent.com/assets/103496/20734876/38777cde-b651-11e6-8b92-c648bfcb1f8a.png)

Not sure I follow the overlapping part though. Would there be overlapping with the above design? 

Also can we have a little more padding like the mock above? Mainly on the left hand side.
