### ISSUE TITLE
Standardize icon + text link pairings

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#185]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), change all icon + text link pairings to a blue non-underlined icon + blue underlined text. For standalone trash icons please add delete next to it with the same format. 

![image](https://cloud.githubusercontent.com/assets/103496/20725204/f028fb04-b625-11e6-8c4b-bfd14c06a29e.png)

![image](https://cloud.githubusercontent.com/assets/103496/20725194/e4b89d7e-b625-11e6-8f64-36d93700ae58.png)

**Comment by webinista** [comment]
@angel confirming that this includes the _Attach a file_ button.
<img width="131" alt="screen shot 2016-12-14 at 12 34 09 pm" src="https://cloud.githubusercontent.com/assets/354277/21199737/a20b7fac-c1f9-11e6-8d46-013b7f4277a9.png">

**Comment by ahelkit** [comment]
@webinista Yeah, thanks for confirming.
