### ISSUE TITLE
Change additional subject line to a label

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#186]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), remove the placeholder text and add a label above that field to say "Additional subject line"

![image](https://cloud.githubusercontent.com/assets/103496/20725470/c6ecee0c-b626-11e6-93b8-669d26440e99.png)

**Comment by webinista** [comment]
Questions:

- These labels are currently bold. Should they remain so?
- What does the error state look like?
- Should these fields stack on mobile?

**Comment by ahelkit** [comment]
@webinista 

1. No, labels are going to be regular to align with our design patterns discussed [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/183) under nconsistencies 6. 

2. I think it would look like this:
![image](https://cloud.githubusercontent.com/assets/103496/20732703/cbe8a324-b644-11e6-87b4-dc644bd2a3ce.png)

3. They should stack in mobile but I think it should be grouped together with the subject line still like how it's above sans the error.

**Comment by webinista** [comment]
What do the errors look like on desktop? Are they going to be positioned beneath the label?

**Comment by ahelkit** [comment]
@webinista Good question. Yeah it looks kind of weird if we make the error state the same as mobile. 

![image](https://cloud.githubusercontent.com/assets/103496/20733761/0e390700-b64a-11e6-9108-e75f59ecb2c1.png)

@melwoodard Would it be weird to have the error be under Subject line? 
![image](https://cloud.githubusercontent.com/assets/103496/20733786/2a0355b2-b64a-11e6-9403-2d9402d38a46.png) since these two fields are related? If you have suggestions to make this better, let me know. Thanks! /cc @gnakm

**Comment by webinista** [comment]
This is what they look like currently.

<img width="821" alt="screen shot 2016-11-29 at 4 00 45 pm" src="https://cloud.githubusercontent.com/assets/354277/20734240/0c3f159a-b64d-11e6-9274-71bc60b23c1e.png">
<img width="805" alt="screen shot 2016-11-29 at 4 00 36 pm" src="https://cloud.githubusercontent.com/assets/354277/20734239/0c3e20ea-b64d-11e6-8f7a-6bfa5026bffd.png">

<img width="379" alt="screen shot 2016-11-29 at 4 01 36 pm" src="https://cloud.githubusercontent.com/assets/354277/20734254/228c6ffa-b64d-11e6-9183-ad6f1ea6e035.png">
<img width="381" alt="screen shot 2016-11-29 at 4 01 26 pm" src="https://cloud.githubusercontent.com/assets/354277/20734255/228eedf2-b64d-11e6-9ae2-6347a9d19013.png">

**Comment by ahelkit** [comment]
@webinista Oh, that works for me! That solves the problem I was having. I didn't realize we had the note above. I like that. Thanks! 

Oh can you remove the colons while you're working on the labels and can there be a little more space between the two form fields? They seem a little too tight.

**Comment by webinista** [comment]
@angel Is this sufficient space? (It's `2rem` or `20px`) <img width="338" alt="screen shot 2016-11-30 at 1 15 56 pm" src="https://cloud.githubusercontent.com/assets/354277/20772733/7ea1ec82-b703-11e6-93c5-7a77ac2a3406.png">
