### ISSUE TITLE
Advanced search date range

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#187]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), date fields should remain side-by-side at a fixed width on mobile instead of defaulting to 100% width.

**Comment by webinista** [comment]
Defaulted to 100% width as a fix for department-of-veterans-affairs/messaging-fe#171. I think it's possible to get them to sit on one line, though.
