### ISSUE TITLE
Moving a message to a folder doesn't increment its count in settings

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#189]
Steps to reproduce:
1. Move a message from 'Inbox' to a personal folder.
2. After a successful move, go to 'Manage folders'.
3. The selected folder from the move retains its count from the first time it loaded.

**Comment by eli-lewis** [comment]
No counts showing except for drafts and count in drafts is inaccurate (per screenshot, drafts count is 3 but there are two messages in the folder
![folder count](https://cloud.githubusercontent.com/assets/23019174/20757199/59585c92-b6e3-11e6-9919-f5dd94a03202.GIF)

**Comment by U-DON** [comment]
@eli-lewis The counts I'm referring to are those in the settings page when you click 'Manage folders'. But yes, the count next to Drafts is also tangentially related.

**Comment by eli-lewis** [comment]
@U-DON leave this issue here or open a new one?

**Comment by U-DON** [comment]
I think it's separate enough to warrant its own issue.

**Comment by eli-lewis** [comment]
new issue added #195
