### ISSUE TITLE
Saving a new draft doesn't increment the count for the Drafts folder

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#195]
No counts showing except for drafts and count in drafts is inaccurate (per screenshot, drafts count is 3 but there are two messages in the folder
folder count
![folder count](https://cloud.githubusercontent.com/assets/23019174/20794416/33da0a8a-b79a-11e6-856a-357d0ea5a698.GIF)

**Comment by U-DON** [comment]
It's as designed that there are no counts on folders besides Inbox and Drafts. The count for Inbox should be the number of unread messages, and the count for Drafts should be the number of drafts. The bug is that Drafts doesn't keep its count up to date when you add or remove drafts.
