### ISSUE TITLE
Compose message - all fields are different lengths

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#198]
Based on the [feature audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/30), the fields are all different lengths. 

Let's have the:
1. "To" field be the same with as the message field. We know this is long, but it worked better than 50% across since that would cut off health care team names. 
2. Change the "Subject line" and additional subject line to fit 50/50. 

![image](https://cloud.githubusercontent.com/assets/103496/20779728/2ad84f42-b72b-11e6-949a-26f0aab610a1.png)

**Comment by webinista** [comment]
Screen shot for posterity. @angel if you have any more design changes, please open a new ticket.

![screen shot 2016-12-16 at 11 23 51 am](https://cloud.githubusercontent.com/assets/354277/21275547/25b13110-c382-11e6-89f9-5462f241191b.png)

**Comment by ahelkit** [comment]
@webinista looks great! Thanks!
