### ISSUE TITLE
ToggleThread component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#20]
Button that expands or collapses all messages in a thread. Only available on [wide screen view](https://marvelapp.com/159dfd8#14605165)

Closed view:
<img width="129" alt="screen shot 2016-09-01 at 1 48 31 pm" src="https://cloud.githubusercontent.com/assets/354277/18183781/d184a7a0-704a-11e6-999e-e0becf281db0.png">

Open view:

<img width="127" alt="screen shot 2016-09-01 at 1 49 05 pm" src="https://cloud.githubusercontent.com/assets/354277/18183794/e2c6dfb0-704a-11e6-940a-5c041fb318c8.png">

Blocks #18 (MessagePage component)

**Comment by webinista** [comment]
@angel @gnakm Are these arrows available as FontAwesome icons? Does it make more sense to use the same arrows that we're using for _Advanced Search_ and the like?

**Comment by ahelkit** [comment]
@webinista those arrows are available as FontAwesome icons. Let me try them with the advanced search arrows and get back to you!

**Comment by ahelkit** [comment]
@webinista let's go with the same arrows we used for advanced search. I've updated the prototypes to reflect that.
