### ISSUE TITLE
Unable to send messages when there is an attachment

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#204]
![failed to send](https://cloud.githubusercontent.com/assets/23019174/21369827/c684c15e-c6d6-11e6-8597-9a90a92eeb71.PNG)

Can successfully send a message without  a message.  Failure to send when there is an attachment.

**Comment by ayaleloehr** [comment]
Error returned from the API when sending a message with an attachment is:

```
{"errors":[{"title":"Operation failed","detail":"Unknown application error occurred","code":"VA900","source":"Unrecognized field \"message\" (Class gov.va.med.mhv.sm.api.transfer.PatientMessageTO), not marked as ignorable\n at [Source: org.apache.cxf.transport.http.AbstractHTTPDestination$1@1c2bed7a; line: 1, column: 13] (through reference chain: gov.va.med.mhv.sm.api.transfer.PatientMessageTO[\"message\"])","status":"400"}]}
```

This seems like a problem with MHV, so I have emailed their technical team to see if they have seen this before or know what it is.

**Comment by ayaleloehr** [comment]
MHV has requested "Could you run it with content-type=multipart/form-data instead of application/json"

@mphprogrammer has the ball here and is working this to see if it's a backend issue on our side.

**Comment by eli-lewis** [comment]
tested and verified.  Closing issue
