### ISSUE TITLE
Deleting drafts sends user in loop

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#206]
1. Go to compose a new message and save it as a draft
2. Go to the drafts folder and open the saved draft
3. Click delete
4. Click "Yes, delete forever"

Expected: Draft is deleted and user is taken back to the drafts folder
Actual: Draft is deleted but user is taken through many different loading screens, eventually ending up at something that looks like this (note the URL):

<img width="1162" alt="screen shot 2016-12-21 at 1 19 26 am" src="https://cloud.githubusercontent.com/assets/4719765/21379397/b2a2afc6-c71b-11e6-81dd-b5e478bc4d4c.png">

Note: this same behavior happens whether you hit the delete button at the top or the bottom of the draft (seen as both the red circles below) so needs to be fixed in both places. 

<img width="1131" alt="screen shot 2016-12-21 at 1 18 19 am" src="https://cloud.githubusercontent.com/assets/4719765/21379418/d9b33a18-c71b-11e6-8901-a2c3b7695954.png">

**Comment by U-DON** [comment]
May be due to session timing out if the request is resulting in 401.

**Comment by ayaleloehr** [comment]
I don't believe it's a session timeout issue. This was just after logging in and happened multiple times in a row (with other API requests working in between)

**Comment by U-DON** [comment]
@ayaleloehr Can you confirm if this is still happening?

**Comment by ayaleloehr** [comment]
No longer happening! Thanks for checking!

**Comment by bshyong** [comment]
Sweet; guess it was the submit event breaking things
