### ISSUE TITLE
ButtonDelete

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#22]
Button that deletes an individual message. Should have two modes: full and compact. Compact view is just the icon. Full shows _Delete_ text

<img width="75" alt="screen shot 2016-09-01 at 1 52 55 pm" src="https://cloud.githubusercontent.com/assets/354277/18183920/6b7e07a2-704b-11e6-89db-d95c414bf384.png">

Compact state (lower right corner)
<img width="718" alt="screen shot 2016-09-01 at 2 22 46 pm" src="https://cloud.githubusercontent.com/assets/354277/18184829/9a91d204-704f-11e6-88c0-3f0163a9c6da.png">
#### Blocks
- #18 
- #31 
- #3 
- #50

**Comment by webinista** [comment]
@angel I wanted to get your feedback here. We didn't have a `:hover` state for the Delete button, so I added one that is basically the `usa-button-outline` style. Are you okay with that? Would you like a different treatment?

Default state (left icon is the 'compact' view, right is the full/default view):

<img width="177" alt="screen shot 2016-09-12 at 5 43 47 pm" src="https://cloud.githubusercontent.com/assets/354277/18457802/8d13ec7e-7910-11e6-867f-b4c64ae0fe7d.png">

`:focus`/`:hover` state

<img width="197" alt="screen shot 2016-09-12 at 5 44 06 pm" src="https://cloud.githubusercontent.com/assets/354277/18457803/8d173136-7910-11e6-9dfd-b80a121f34e4.png">

**Comment by ahelkit** [comment]
@webinista Let's have the hovers be blue but no outline. That applies for all the buttons that look like this delete button. Thanks!
