### ISSUE TITLE
MessagePageHeader

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#24]
Contains:
- Message title
- Number of messages in thread
- ToggleThread component #20 
- Print component #21 
- Delete button #22 
- BackLink component (#23; Mobile only)

<img width="712" alt="screen shot 2016-09-01 at 1 55 21 pm" src="https://cloud.githubusercontent.com/assets/354277/18184005/c932d210-704b-11e6-9198-2ef5e5c6a6e3.png">
#### Prototypes
- [Wide screen](https://marvelapp.com/159dfd8#14605162)
- [Narrow screeen](https://marvelapp.com/11jc4c2#14680021)
#### Blocks
- #18

**Comment by webinista** [comment]
@angel Is there a design for the printed message view?

**Comment by ahelkit** [comment]
@webinista there is not a design for it. I can design one though. What I was thinking for the print view was a flat view of the email with all the messages in the thread expanded along with the message details for each message in that thread.I can work on this tomorrow and attach it here.
