### ISSUE TITLE
MessageList container component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#3]
View for each list of messages. This should accommodate the Inbox, Drafts, Sent, and Deleted views.
- Unread messages should be bold
- Read messages should be normal weight text
- Messages are sortable by date

<img width="739" alt="screen shot 2016-09-01 at 1 19 59 pm" src="https://cloud.githubusercontent.com/assets/354277/18182942/e45b77b8-7046-11e6-9f1d-4d2f02b96acd.png">

Related to #5

**Comment by webinista** [comment]
Should investigate [Griddle](https://griddlegriddle.github.io/Griddle/) for this.

**Comment by U-DON** [comment]
Per [Slack discussion](https://dsva.slack.com/archives/vetsgov-sm/p1473351400000097), 'from' and 'category' should also be sortable fields.

**Comment by webinista** [comment]
Checkboxes are going away in favor of a MoveTo component on the right side of the screen. See issue #44.

**Comment by webinista** [comment]
@U-DON Is this done enough to close?

**Comment by U-DON** [comment]
Yeah, I guess we can close this. We can create new issues for the sorting and adding any fields that are missing.
