### ISSUE TITLE
CharacterCount

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#32]
Counts down remaining characters as the veteran adds a character to the message field.
- Start value is 2000

<img width="178" alt="screen shot 2016-09-01 at 2 31 08 pm" src="https://cloud.githubusercontent.com/assets/354277/18185112/edb23662-7050-11e6-8284-a7eaeb09c0a2.png">

Blocks #31

**Comment by webinista** [comment]
@angel What should happen when the 'Characters left' number reaches 0? 

The counter could stay at 0 and prevent the veteran from adding more text. 

Another possibility: The counter could go negative. Text could turn red to indicate a problem. And we can disable the Send and Save buttons until the message gets shortened.

**Comment by ahelkit** [comment]
@webinista I think it's a better experience for it to go negative so then a Veteran can finish their thought and then trim down. 

The character count should:
1. Go negative
2."Characters left: -120" should turn red
3. The text that is over the count to highlight red

![image](https://cloud.githubusercontent.com/assets/103496/18600816/7072fea0-7c14-11e6-853d-1af799d4e090.png)

I also think the send and save button should be disabled until the message gets shortened. Thanks!

**Comment by webinista** [comment]
Item # 3 is going to take some work. Let's come back to that.

Update: Tracking work on part 3 in #61

**Comment by ayaleloehr** [comment]
👍 Agreed on not prioritizing 3 right now. Let's get the basic functionality in first!
