### ISSUE TITLE
[Parent Issue] MessageCompose component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#35]
Should contain: 
- From: Veterans name
- MessageRecipients #36 
- MessageCategory #37 
- Subject line `input type=text`
- Message `textarea` component #38
- MessageSend component #31 

Narrow screen view should have:
- Top control bar that contains:
  - New message
  - Send button
  - Cancel button 
- [Narrow screen](https://marvelapp.com/11jc4c2#14680026) 
- [Wide screen](https://marvelapp.com/159dfd8#14605166) 
#### Questions
- Is there a _New message_ vs a _Reply message_ mode? 
  - What should / shouldn't the Reply message screen have compared to the New message screen?

**Comment by ahelkit** [comment]
@webinista
1. For new messages, a Veteran should be able to edit all field except from. 
2. For when a Veteran replies when viewing a message nothing should be able to change in the reply box except the message. 
3. When a Veteran goes into Drafts: 
-    a. If it's a new message draft then everything should still be editable except from. 
-    b. If it's a reply message draft then from and to should not be editable.

**Comment by webinista** [comment]
Send, Delete, Save Drafts is blocked by the API. Should be available by next week.

**Comment by ayaleloehr** [comment]
Triaging emails. I believe these are now unblocked; please let me know if they are not!
