### ISSUE TITLE
MessageRecipients component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#36]
Select menu containing list of appropriate VA personnel.

<img width="583" alt="screen shot 2016-09-01 at 3 01 23 pm" src="https://cloud.githubusercontent.com/assets/354277/18185987/05c885fe-7055-11e6-82dd-56c2c374a684.png">
- Can probably repurpose `ErrorableSelect` from HCA.

[Prototype](https://marvelapp.com/159dfd8#14605166)

Blocks #35

**Comment by webinista** [comment]
@angel / @gnakm: Will the recipient list default to a single team member?

**Comment by gnakm** [comment]
Hey away from my laptop now but could we make the top default "Select from your health care team."

**Comment by webinista** [comment]
We can't do _that_ without a bit of refactoring. I'll take a crack at it soon. But I'm going to save it for later.
