### ISSUE TITLE
ToggleComponent

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#41]
On/Off widget used on the Settings page. [Prototype](https://marvelapp.com/159dfd8/screen/14605154)

Blocks #17

**Comment by webinista** [comment]
@jcmeloni This is something that was specced, but not built because we removed the feature. Not sure whether we're adding it as a feature later, however. Makes sense to me that we'd still track. Should this be closed? Moved to the -website or .gov-team repo for tracking?

**Comment by ayaleloehr** [comment]
Going to close until we have an API that can actually support this, as until then this is not actionable.
