### ISSUE TITLE
ModalSettingsUpdateEmail component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#42]
On the [settings page](https://marvelapp.com/159dfd8/screen/14605154), triggered when the veteran tries to edit their e-mail address.

<img width="665" alt="screen shot 2016-09-08 at 4 53 44 pm" src="https://cloud.githubusercontent.com/assets/354277/18370811/dc871918-75e4-11e6-9065-31590fc23bb4.png">
- Should validate email address when entered
- Can probably import and adapt form field components from `/common`

**Comment by webinista** [comment]
Marking as invalid for now because we do not yet have notifications available in the API

**Comment by eli-lewis** [comment]
@ayaleloehr can this be closed?

**Comment by ayaleloehr** [comment]
This is not actionable at this time, as the API doesn't support this, so closing.
