### ISSUE TITLE
NoticeBox component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#43]
Non-dismissible box that contains important things for the veteran to know.

<img width="266" alt="screen shot 2016-09-08 at 5 00 43 pm" src="https://cloud.githubusercontent.com/assets/354277/18371001/061d97a6-75e6-11e6-8872-bdde58337ca9.png">

See comments on [issue #4](https://github.com/department-of-veterans-affairs/messaging-fe/issues/4#issuecomment-245779155)

**Comment by webinista** [comment]
This component will probably change soon.

**Comment by ahelkit** [comment]
The notice box will show up at the bottom when a Veteran is viewing or composing a message or draft, where we think the info in that box is most relevant to the Veteran.

Here is what the **desktop** version looks like:
![view message](https://cloud.githubusercontent.com/assets/103496/18483029/5b8893ee-7997-11e6-8c65-e5624a33d090.png)

Here is what the **mobile** version looks like (full bleed):
![image](https://cloud.githubusercontent.com/assets/103496/18483085/97e4d1ea-7997-11e6-9009-880e1f4c09a7.png)

Font Awesome icons we're using:
- fa-calendar-o `[&#xf133;]`
-  fa-user-md `[&#xf0f0;]`
