### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#46]
FAQ with an Accordion pattern.

Lowest priority. 
##### Prototypes
- [Closed state](https://marvelapp.com/1bdd199/screen/15055082)
- [Open state](https://marvelapp.com/1bdd199/screen/15055083)

**Comment by webinista** [comment]
@angel @gnakm Is this content for this issue being tracked somewhere else?

**Comment by gnakm** [comment]
We decided to punt on the help page because we won't be displaying helpful information. @angel Tagging you to confirm and close.

**Comment by ahelkit** [comment]
@gnakm Yes, closing for now.
