### ISSUE TITLE
ModalCreateNewFolder component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#47]
![screen shot 2016-09-09 at 12 32 05 pm](https://cloud.githubusercontent.com/assets/354277/18400142/7018dd70-7689-11e6-92a6-8f6f8549ae1c.png)

Similar to: 
- #42 

Blocks #44, #67, #68.

**Comment by ahelkit** [comment]
If a Veteran puts a name of a folder in the field that already exist then the error would show up like so:
![create a new folder error](https://cloud.githubusercontent.com/assets/103496/18532209/7fa5fcdc-7a8f-11e6-81d2-df27dc1742c1.png)

You can see how that looks on marvel here too: https://marvelapp.com/1bdd199/screen/15044682.

The click order is:
1. move
2. create a folder
3. fill in text box
4. gets an error, fill in text box with new name
5. success!

I know we're not creating a folder when using the move, but the create modal would be the same for when you click the "+ create folder" link from the side nav or manage folders page.
