### ISSUE TITLE
MessageFrom component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#53]
Probably blocked by authentication API availability.

![MessageFrom](https://cloud.githubusercontent.com/assets/354277/18185987/05c885fe-7055-11e6-82dd-56c2c374a684.png)

Need to retrieve and print the current veteran's name.

Related to department-of-veterans-affairs/vets-website#2847

**Comment by webinista** [comment]
I'm tagging you with this AlexYL. Is it possible to retrieve the current veteran's name? Or are we still blocked by authentication?

**Comment by ayaleloehr** [comment]
We do not have the Veteran name yet, nor will we within the next week or two at least. Can we hard code something in there for now and add a TODO saying we need to come back to it?
