### ISSUE TITLE
Add error checking for Compose form

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#55]
- From field: can't validate yet. (See #83)
- Subject line: 
  - Category: required
  - Subject: optional, max length 512 characters (See #82) 
- Attachments: 
  - Max of 4 files
  - 3MB max per file
  - 6MB total max
- Message body/text: required, enforce > 0 characters

Blocks #35 
Blocked by #90

**Comment by webinista** [comment]
@ayaleloehr Are there API restrictions on characters or length for any of these fields?

**Comment by ayaleloehr** [comment]
Have an email out asking this (and 13 other similar questions). Will report as soon as I hear back.

**Comment by webinista** [comment]
Questions: 
- Should we concatenate the message and subject on the front-end before sending?
- Should we force a character minimum length for the message body since it's required?

**Comment by ayaleloehr** [comment]
Sounded from another comment (not sure on the issue number) that you have a path forward on concatenation (not doing it).

I think forcing >0 characters for message body makes sense. Either the "send" button could be disabled when there is an empty body or a validation could happen on clicking "send" where it pops up a modal if the body is empty saying "you can't send a blank message."  Thoughts on which of those is better (or another option) @angel ?

**Comment by ahelkit** [comment]
@ayaleloehr I agree with forcing > 0 characters makes sense. As for the other part, I think disabling is better. @webinista and I have talked about it. Here's what that would look like this: https://marvelapp.com/1bdd199/screen/15044675 and if you click the message area you can see the active state.

**Comment by webinista** [comment]
@angel I ended up making a lot of CSS and markup work to accommodate error messages. These are patterned after our existing error styles, but with the layout adjusted a bit to accommodate the differences between the Compose UI and established USWDS/VA styles. 

Here's what that looks like now (not the actual error messages, this is just to show the example).

### Desktop

<img width="827" alt="screen shot 2016-10-04 at 4 55 27 pm" src="https://cloud.githubusercontent.com/assets/354277/19096799/45bf7bcc-8a54-11e6-9438-cbc57822d9f5.png">

### Small devices

![screen shot 2016-10-04 at 16 56 45-fullpage](https://cloud.githubusercontent.com/assets/354277/19096825/87b9b006-8a54-11e6-8785-fbf968ac2823.png)

**Comment by ahelkit** [comment]
@webinista 

That's a lot of red!

### For Desktop:
- Add a red border around the message box to be consistent with the other boxes
- The additional subject line text box is optional unless other is selected so it doesn't need to have a red border if left blank without a subject
- I changed the error messaging a little, not sure it's completely the right language. 
  - "Please select a health team" (shortened it.)
  - "Please select a subject" (when nothing is selected)
  - "Please add additional information" (when other is selected but the text box is left empty)
  - "Please enter a message"

Here's what that would look like:
![image](https://cloud.githubusercontent.com/assets/103496/19126687/c259d596-8af0-11e6-9194-88d762bd1cfa.png)

![image](https://cloud.githubusercontent.com/assets/103496/19126705/d2e0e8fa-8af0-11e6-8dd0-3c18b421e4cc.png)

### For Mobile:
- Could we break up the line  so it's in the same style as the desktop like so?:

![image](https://cloud.githubusercontent.com/assets/103496/19125878/8c389cb6-8aed-11e6-92ff-af7b091af75f.png)
![image](https://cloud.githubusercontent.com/assets/103496/19125911/ad88b068-8aed-11e6-9160-641905940ab9.png)

Let me know of these changes make sense. Thanks!

**Comment by ahelkit** [comment]
@webinista 

Also, don't know if this is the right issue but I'll put it here for now and you can tell me if I need to move it, but @U-DON mentioned that message might fail to send. I think the error message for that would look like this: 

![image](https://cloud.githubusercontent.com/assets/103496/19165160/9e8d229a-8bb7-11e6-9d33-cd65e43323b7.png)

Not sure if the language is right, but that's the gist of it.

**Comment by webinista** [comment]
@angel Yep. We already have that built :-)

**Comment by ahelkit** [comment]
@webinista of course you did! Just wanted to make sure I wasn't a blocker. Thanks!
