### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#6]
Similar to the GrowableTable component from HCA. 

Blocks #3, #50, #17

**Comment by webinista** [comment]
Investigating how well [Griddle](https://griddlegriddle.github.io/) fits our needs

**Comment by U-DON** [comment]
At the least, we can re-use the SortableTable component from Rx. It's decoupled from the Pagination, so we could have it work with the prev/next buttons as well.

I suspect the API will provide the messages in paginated form again, which might not work with most fully-client-side solutions out there.

**Comment by webinista** [comment]
I think what we have complete enough to close this task.
