### ISSUE TITLE
Specify disabled button state styles

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#62]
None currently exist in the codebase. This would be a new pattern. Just need guidance about opacity, colors, etc.

Blocks #61. Blocks #32

**Comment by ahelkit** [comment]
@webinista I tried to lower the opacity but it didn't pass WCAG AA, so I changed it to be a gray instead. I was going to use the disabled button from the U.S. Web Design Standards, but that gray background doesn't pass against our light gray box so I went with same gray as the border and color of the "Save as button" like so: 
![image](https://cloud.githubusercontent.com/assets/103496/18649405/2c631c74-7e74-11e6-81c7-b1308f2ceb4e.png)

Here's what it would look like in action: https://marvelapp.com/1bdd199/screen/15044675. You can just click the message box to go back and forth. 

### The colors used are:

**Send button:**
background color: #5B616B
color: #ffffff

**Save as draft button:**
border color: #5B616B
color: #5B616B
