### ISSUE TITLE
Delete draft flow: Compose message versus reply to message

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#63]
When a veteran deletes a draft from the Compose screen or Drafts folder, they're returned to the Drafts folder. What happens when they delete a draft that was started as a reply?  
### Compose flow is:

Compose → Delete draft → Confirm deletion → Drafts folder
### Reply flow should be:

Reply → Delete draft → Confirm deletion → _???_

I'm also assuming that the compose flow is similar to the Drafts flow, e.g.:

Drafts → View Draft  → Delete draft → Confirm deletion → Drafts folder

Is that correct?

**Comment by ahelkit** [comment]
@webinista Can we do the following?

### Compose flow should be:

Compose → Delete draft → Confirm deletion → Whatever folder the Veteran clicked compose from. 

### Reply flow should be:

Reply → Delete draft → Confirm deletion → The reply box clears and stays at that message.

**Comment by webinista** [comment]
In either case, need to display Alert message at the end of it that confirms the action.
Related to #77
