### ISSUE TITLE
Expand individual messages in a thread

### ISSUE THREAD

**Issue by ahelkit** [department-of-veterans-affairs/messaging-fe#65]
Clicking on the gray area should expand that individual message: 
![image](https://cloud.githubusercontent.com/assets/103496/18679515/cde94956-7f14-11e6-9081-897431fadebb.png)

**Comment by U-DON** [comment]
Should clicking on the message when it's expanded also collapse it?

**Comment by ahelkit** [comment]
@U-DON Yes, when clicking in the header area where the from/to and time are it would collapse.

**Comment by U-DON** [comment]
@angel What state should the expand all/collapse button be in if some messages are expanded and some are collapsed? I would think "expand all" if everything is collapsed and "collapse all" if everything is expanded, but not sure about if they's split.

**Comment by ahelkit** [comment]
@U-DON If there are any messages that are still collapsed then the state should be "expand all".
