### ISSUE TITLE
Add error checking for ModalCreateFolder

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#67]
Need to check two things:
- [x] Is the field empty?
- [x] Does the folder already exist?
- [x] Does the name contain disallowed characters?
- Setting a maxlength on the client side to prevent this. ~~Does the name field exceed the number of allowed characters?~~

Blocked by #47.

**Comment by webinista** [comment]
@saneshark @mphprogrammer @ayaleloehr Will particular characters be excluded from folder names?

**Comment by ayaleloehr** [comment]
Just looked up the API documentation... "The folder name should only contain letters,
numbers, and spaces".  Let's assume that means English characters for letters too.

**Comment by webinista** [comment]
Is there a max character length?

**Comment by saneshark** [comment]
I'm not aware of one looking at the specs. We're not enforcing one on our end, but MHV might be enforcing one that we are not aware of. I can do a quick test and see if you want.

**Comment by webinista** [comment]
Yes please :-) (Although Alex YL said that he's awaiting answers to some questions from MHV about this exact topic.)

**Comment by saneshark** [comment]
So there does appear to be a limit. The error that will be returned is:

``` json
{
  "errors": [
    {
      "title": "Operation failed",
      "detail": "Mailbox service error",
      "code": "900",
      "status": 400
    }
  ]
}
```

**Comment by saneshark** [comment]
The limit appears to be 50 characters. 

This was the absolute largest I was able to get through: 

``` json
{ "folder": { "name": "12345678901234567890123456789012345678901234567890" } }
```

**Comment by saneshark** [comment]
If you ever see an error that is `Status 400 Bad Request` and the errors json "title" is "Operation Failed" or having minor code "900" -- the "detail" will have as descriptive an explanation as we can possibly provide on our end. This is a very generic class of error even on MHVs side. They have more descriptive messages, but this is their generic catch all, and the best we can do is pass it back. That minor code is ours though, so you can reliably expect that to remain the same -- only the "detail" in that message is subject to change. 

This is basically ClientResponse Error, if it would be helpful we can change "Operation failed" to be "Client responded with operation failed" or something instead. It basically means something happened that is outside of our control, but it was not a 500 error.

**Comment by saneshark** [comment]
@webinista Please open issues for any "Operation failed" errors that you encounter that you think we could reliably check and test for server side. This one is an example of a very trivial one, I would be more than happy to validate for on our end so that we can return a much more descriptive error message.
