### ISSUE TITLE
Remove 'From' from the "Select from your health care team" label

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#72]
Hold off on this until we have new UX/mockups.

**Comment by webinista** [comment]
Marking as invalid, but leaving open. This may change.

**Comment by webinista** [comment]
@gnakm @angel @staceylanger This was based on stakeholder feedback from awhile ago. Did we ever say definitively whether we're doing this? Is it safe to close this issue?

**Comment by ahelkit** [comment]
@webinista I would remove the "from" so it's just "Select your health care team". Thanks!

/cc @staceylanger

**Comment by webinista** [comment]
I am not sure this is relevant anymore. I think we removed this in favor of just a "To:" field?
