### ISSUE TITLE
Add AlertBox confirmation for Create New Folder flow

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#81]
Need to differentiate between when `ModalCreateNewFolder` gets triggered during a `MoveTo` operation versus creating one anew from the `FolderNav` button.

See the [MoveTo confirmation flow](https://marvelapp.com/1bdd199/screen/15044682). `FolderNav` flow should be similar, but end with a different message. Maybe "Successfully created {new folder name}," or "You now have a folder named {new folder name}."

Blocked by #68

**Comment by U-DON** [comment]
I think the alert from the folder creation itself can be the same in both cases, and the actual move would have its own alert as well. The actual move would presumably always trigger its alert after the folder is created, so that alert would overwrite the one from the folder creation.

**Comment by webinista** [comment]
According to the prototype linked above, when the veteran creates a new folder using _Move To → Create New Folder_, the confirmation message should read "Your message has been moved to {folder name}." The folder creation action and message move action should happen in one step from the veteran's perspective.
