### ISSUE TITLE
Integration and unit tests

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#86]
We need 'em. Making sure we're tracking the task here. I'll turn these into separate GitHub issues, but want to use this as a parent issue to brainstorm what we'll test, and later, to group the subtasks. 
### Likely unit tests
- [ ] Creating a folder
  - [ ] Showing the modal
  - [ ] Hiding a modal
  - [ ] Reacting to user input
    - [ ] Does disallowing certain characters work? (Allows a-z, 0-9, space character, case-insensitive)
    - [ ] Does check for an existing folder work?

**Comment by ayaleloehr** [comment]
And unit tests!

**Comment by bshyong** [comment]
@U-DON is this already in progress somewhere, or does it still need to be done?

**Comment by U-DON** [comment]
@bshyong Not really. It was more of an umbrella issue. I'm not sure how we wanna track the remaining ones.

**Comment by bshyong** [comment]
Got it; I'll check this issue against our existing test coverage and figure out if we need to add anything else before we can close this issue. I think we have pretty good coverage now, so we probably don't need too much more.

**Comment by U-DON** [comment]
I ran `npm run test:coverage` the other day and found a bunch of modules that haven't been fully covered yet. I think this issue can be closed in favor of a new running issue that's based on the results of the coverage report.

**Comment by bshyong** [comment]
Makes sense
