### ISSUE TITLE
Transitions between screens

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#87]
The MHV API often seems to take 2-3 seconds to return a response. This makes for an awkward state in both Rx and SM currently, where the page loads, the user sees no data, then a couple seconds later the data fills in.  We have discussed having some sort of loading screen or smoother transition, but I couldn't find anywhere this was being tracked. 

Is this on your radar @gnakm and @angel (tagging both of you since it impacts both SM and Rx!)?

**Comment by gnakm** [comment]
@ayaleloehr yes! We have an issue for it here: https://github.com/department-of-veterans-affairs/kudos-team/issues/169 I'm on it.

**Comment by ayaleloehr** [comment]
Sorry! I'm a victim of only looking at labels!  Closing. Thanks @gnakm
