### ISSUE TITLE
Automatically saving drafts?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#88]
I don't believe this is an issue we have actively discussed before, so wanted to bring it up. 

@angel any thoughts on if we should automatically save a draft of a message as a user is creating it?  If so, how often might this occur and what should it look like to the user?  I am not sure what MHV does in this regard today (but I do know they have a much shorter timeout than we plan to!). 

@U-DON and @webinista I also have no clue on the difficulty of this from an implementation perspective so interested in your thoughts as well!

**Comment by U-DON** [comment]
I think it's doable, but not so simple that I would want to definitely tackle it for the first release. Depends on what it would look like.

**Comment by ahelkit** [comment]
@ayaleloehr @U-DON @webinista I think automatically saving drafts would be great as long as it doesn't slow things down for Veterans and they don't notice it happening in the background as they are typing.  If we're able to do that then I think saving every minute would be good or if we can detect when the Veteran stops typing and save it then. We could remove the "save as draft" button and have text that shows that it's been saved. Something like "Draft saved at 11:44am". I can mock it up and share it.

**Comment by ayaleloehr** [comment]
So reading both comments ^, I say getting mockups for autosaving at some point would be good but it's not a rush and we should implement what is in the current mockups now for our MVP.  Implementing what is currently in the mockups will be the technical basis of later allowing auto-saving, so there will be little duplicative work in first implementing what is in the current mockups (with "save as draft" button) and later iterating to having it autosave.  

Please give this a 👍  if you agree with this approach and 👎  if you disagree (comments obviously welcome as well).

**Comment by ayaleloehr** [comment]
Thanks for the replies. Closing for now then, as this feels resolved!
