### ISSUE TITLE
Messaging CSS is 1.3MB

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/messaging-fe#94]
This is unacceptable. De-duping FontAwesome's inclusion (see department-of-veterans-affairs/vets-website#3266) and removing inline SVG would bring us down to about 400K. 

That's still huge, but it's well under 1MB. Will update this thread with other potential optimizations. (Shorter class/id names would probably help here.)

**Comment by eli-lewis** [comment]
@webinista any updates on this?

**Comment by webinista** [comment]
Yes. We can finally close it. I'm sure there are other optimizations we can make, but the two big blockers have been addressed.
