### ISSUE TITLE
Mobile layout for replies and drafts

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/messaging-fe#97]
Different screen when replying, with all information available (sender, recipient, category, subject) but not editable.

Reply screen:
https://marvelapp.com/12c67dg/screen/15042062

Different button text on thread page to edit drafts:
https://marvelapp.com/12c67dg/screen/15042035

**Comment by webinista** [comment]
@U-DON Can this be closed?

**Comment by U-DON** [comment]
@webinista Not yet; the thread view still needs a way to reply in mobile.
